### ISSUE TITLE
"Create Octopus Release" started failing with Unrecognized command arguments: 

### ISSUE THREAD

**Issue by danielab** [OctopusDeploy/OctoTFS#224]
After Friday 11.03.22 our "Create Octopus Release" task v3 started failing in our Azure Devops pipeline. There has been a change in the Octo.exe create-release command. **An empty argument "" has appeared**. We have not done any changes since last successful run.

Previous working output from our pipeline logs of the azure devops task: 

`c:\choco\bin\Octo.exe create-release "--project=Foo.Bar API" --releaseNumber=2022.3.4.20 --channel=Default --server=http://foo-bar.biz/ --apiKey=*** --enableServiceMessages --releaseNotesFile=D:\w\6\2277\s\release-notes-4706a450-9bbb-11ec-a119-fb175bb88688.md --packageversion 2022.3.4.20`

Now, the command has changed to (see the double empty quotes after releaseNumber and before channel):

`c:\choco\bin\Octo.exe create-release "--project=Foo.Bar API" --releaseNumber=2022.3.14.20 "" --channel=Default --server=http://foo-bar.biz/ --apiKey=*** --enableServiceMessages --releaseNotesFile=D:\w\5\2500\s\release-notes-60532ff7-9080-4559-9d56-de09af4b8d2e.md --packageversion 2022.3.14.20`

```
Unrecognized command arguments: 

This error is most likely occurring while executing octo as part of an automated build process. The following doc is recommended to get some tips on how to troubleshoot this: https://g.octopushq.com/OctoexeTroubleshooting
Exit code: -1
##[error]"Failed to create release. The process 'c:\choco\bin\Octo.exe' failed with exit code 4294967295
Error: The process 'c:\choco\bin\Octo.exe' failed with exit code 4294967295
    at ExecState._setResult (D:\w\5\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\3.1.27\node_modules\azure-pipelines-task-lib\toolrunner.js:942:25)
    at ExecState.CheckComplete (D:\w\5\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\3.1.27\node_modules\azure-pipelines-task-lib\toolrunner.js:925:18)
    at ChildProcess.<anonymous> (D:\w\5\_tasks\OctopusCreateRelease_4e131b60-5532-4362-95b6-7c67d9841b4f\3.1.27\node_modules\azure-pipelines-task-lib\toolrunner.js:838:19)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
```

YAML definition of the Azure DevOps task:

```yaml
steps:
- task: octopusdeploy.octopus-deploy-build-release-tasks.octopus-create-release.OctopusCreateRelease@3
  displayName: 'Create Octopus Release for master: "$(build.ApplicationName)"'
  inputs:
    OctoConnectedServiceName: 'FooBar Server'
    ProjectName: '"$(build.ApplicationName)"'
    ReleaseNumber: '"$(build.Number)"'
    Channel: Default
    ChangesetCommentReleaseNotes: true
    WorkItemReleaseNotes: true
    DeploymentProgress: true
    AdditionalArguments: '--packageversion "$(build.Number)" --releasenotes "Built from commit $(build.sourceVersion)"'
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
```
 
We are using: Octopus Deploy Command Line Tool, version 7.4.3116
When running this command directly on local machine it works with powershell but not with unix shell.
I have tried to use the task version v4 in azure devops but with same error as above.

Any feedback is appreciated.

**Comment by johnsimons** [comment]
Hi @danielab,

There were a few changes pushed around that time, I am sorry that these are causing issues to you.
I am trying to reproduce this problem, would you be able to "Enable System Diagnostics" and send us the full raw logs?
If the raw logs have sensitive information, [email them to our support email address](https://octopus.com/support). 
<img width="236" alt="image" src="https://user-images.githubusercontent.com/122651/158701638-4ff29b31-5a5b-46bb-8aad-c01fde4db192.png">
<img width="716" alt="image" src="https://user-images.githubusercontent.com/122651/158700751-212f490e-9ac2-46c9-a0f6-4c35fca1b239.png">

I used a hosted agent and copy-pasted your yaml onto a new pipeline, and it seems to work, no extra `""`.

Just wondering what happens if you add the Installer task beforehand?
Here is what seems to work for me:
```yaml
steps:
- task: OctoInstaller@4
  inputs:
    version: '8.0.0'
- task: OctopusCreateRelease@4
  displayName: 'Create Octopus Release for master: "$(build.ApplicationName)"'
  inputs:
    OctoConnectedServiceName: 'octopus main'
    ProjectName: '"$(build.ApplicationName)"'
    ReleaseNumber: '"$(build.Number)"'
    Space: Default
    Channel: Default
    ChangesetCommentReleaseNotes: true
    WorkItemReleaseNotes: true
    DeploymentProgress: true
    AdditionalArguments: '--packageversion "$(build.Number)" --releasenotes "Built from commit $(build.sourceVersion)'
```
