### ISSUE TITLE
UseGuidedFailure does not work in OctopusDeployRelease

### ISSUE THREAD

**Issue by pemaxim** [OctopusDeploy/OctoTFS#319]
Input `UseGuidedFailure` does not work in `OctopusDeployRelease@6`.
It's always `true` whatever input value is set.

Also, the parameter is missing in the documentation [here](https://marketplace.visualstudio.com/items?itemName=octopusdeploy.octopus-deploy-build-release-tasks)

```
- task: OctopusDeployRelease@6
   displayName: Deploy My Project Release
   inputs:
      UseGuidedFailure: false # or "False" does not work.
```

The input parameter is defined as `boolean`. However, the default value is `string`: https://github.com/OctopusDeploy/OctoTFS/blob/main/source/tasks/Deploy/DeployV6/task.json#L77-L82

Also, it's being converted to `boolean` here: https://github.com/OctopusDeploy/OctoTFS/blob/main/source/tasks/Deploy/DeployV6/inputCommandBuilder.ts#L52

Shouldn't it be `string` instead?
